mysite1/blog/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    # url(r'^$', views.post_list, name='post_list'),
    url(r'^(?P<pk>[0-9]+)/$', views.post_detail, name='post_detail'),
    url(r'^new/$', views.post_new, name='post_new'),
    url(r'^post/(?P<pk>[0-9]+)/edit/$', views.post_edit, name='post_edit'),

]

mysite1/mysite1/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from blog import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.post_list, name='post_list'),
    url(r'^post/', include('blog.urls', namespace="post")),

    # url(r'^new/$', include('blog.urls')),
]

mysite1/blog/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone

# Create your models here.


class Post(models.Model):
    author = models.ForeignKey('auth.User')
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

mysite1/blog/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text')

mysite1/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post
from forms import PostForm
from django.utils import timezone
from django.contrib.auth.models import User


def post_list(request):
    now = timezone.now()
    me = User.objects.get(username='bmb')
    posts = Post.objects.filter(author = me).order_by('published_date')
    return render(request, 'blog/post_list.html', {'posts': posts})


def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_detail.html', {'post': post})

def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('post:post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'blog/post_edit.html', {'form': form})

def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('post:post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form})

mysite1/blog/templates/blog/blog.html
{% load staticfiles %}
<html>
    <head>
        <title>Posts</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    </head>
    <body>
    <div id="wrapper">
        <div id="header">
            <div class="logo-text">
                    <h1><a href="/">AUTO_BLOG</a></h1>
                {% if user.is_authenticated %}
                    <h3>Hello, {{ user }}!</h3>
                {% endif %}
            </div>
        </div>
            <div class="page-header">
                {% if user.is_authenticated %}
                <a href="{% url 'post:post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
                {% endif %}
            </div>
            <div class="col-md-8">
                {% block content %}
                {% endblock %}
                </div>
        <div id="footer">
            <div class="footer-text">Click here to tweet! </div>
        </div>
    </div>
  </body>
</html>

mysite1/blog/templates/blog/post_detail.html
 {% extends 'blog/blog.html' %}
    {% block content %}
        <div class="post">
            {% if post.published_date %}
                <div class="publication_date">
                    {{ post.published_date }}
                </div>
            {% endif %}
            <h1 class="post_title">{{ post.title }}</h1>
        {% if user.is_authenticated %}
             <a class="btn btn-default" href="{% url 'post:post_edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
           {% endif %}
            <p class="post_text">{{ post.text|linebreaks }}</p>
        </div>
    {% endblock %}

mysite1/blog/templates/blog/post_edit.html
{% extends 'blog/blog.html' %}

{%  block content %}
    <h1>Create a new post</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>


{% endblock content %}

mysite1/blog/templates/blog/post_list.html
{% extends 'blog/blog.html'%}
{% block content %}
    Info:
    <div class="tweet-right"><blockquote class="twitter-tweet" data-lang="ru"><p lang="en" dir="ltr"><a href="https://t.co/6g2kIQlwwR">https://t.co/6g2kIQlwwR</a></p> Django (@djangoproject) <a href="https://twitter.com/djangoproject/status/739248927778689024">5 июня 2016 г.</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script></div>
{% for post in posts %}
            <div class="post">

                <div class="publication_date">published at: {{ post.created_date }} by {{ post.author }}</div>
                <h2 class="post_title"><a href="{% url 'post:post_detail' pk=post.id %}">{{ post.title }}</a></h2>

                    <div class="post_text">{{ post.text | linebreaks }}</div>

                </div>
            {% endfor %}
{%  endblock content %}
{#{% url 'post_detail' pk=post.pk %}#}